SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS evaluacion_criterios;
DROP TABLE IF EXISTS evaluaciones;
DROP TABLE IF EXISTS estudiantes;
DROP TABLE IF EXISTS proyectos;
DROP TABLE IF EXISTS evaluadores;
DROP TABLE IF EXISTS criterios;
DROP TABLE IF EXISTS grados;
DROP TABLE IF EXISTS niveles;

SET FOREIGN_KEY_CHECKS = 1;
